"use strict";

const fs = require("fs");
const path = require("path");

const CSS_SOURCE_FILES = [
  "00-tokens.css",
  "10-base.css",
  "20-components.css",
  "30-families.css",
  "40-archetypes.css",
  "50-templates.css",
  "60-editor.css",
];

const EDITOR_SOURCE_FILES = [
  "00-shell.js",
  "10-toolbar-history.js",
  "20-export-ui.js",
  "30-edit-format.js",
  "35-template-registry.js",
  "40-media-insertions.js",
  "50-selection-save.js",
  "55-wechat-copy.js",
  "60-export-engine.js",
  "70-start.js",
];

function readFileIfExists(filePath) {
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf-8") : null;
}

function buildFromSources(sourceDir, filenames, joiner = "\n\n") {
  return filenames.map((filename) => {
    const absolutePath = path.join(sourceDir, filename);
    const content = readFileIfExists(absolutePath);
    if (!content) {
      throw new Error(`Missing asset source: ${absolutePath}`);
    }
    return content.trimEnd();
  }).join(joiner).trimEnd() + "\n";
}

function writeIfChanged(filePath, content) {
  const current = readFileIfExists(filePath);
  if (current === content) return false;
  fs.writeFileSync(filePath, content, "utf-8");
  return true;
}

function buildCssBundle(skillDir) {
  const sourceDir = path.join(skillDir, "src", "design-system", "css");
  const body = buildFromSources(sourceDir, CSS_SOURCE_FILES, "\n\n");
  return [
    "/* Generated by scripts/lib/build-assets.js. Edit src/design-system/css/* instead. */",
    body.trimEnd(),
    "",
  ].join("\n");
}

function buildEditorBundle(skillDir) {
  const sourceDir = path.join(skillDir, "src", "editor");
  const body = buildFromSources(sourceDir, EDITOR_SOURCE_FILES, "\n\n");
  return [
    "/** Generated by scripts/lib/build-assets.js. Edit src/editor/* instead. */",
    body.trimEnd(),
    "",
  ].join("\n");
}

function getBuildStatus(skillDir) {
  const cssBundle = buildCssBundle(skillDir);
  const editorBundle = buildEditorBundle(skillDir);
  const cssPath = path.join(skillDir, "assets", "article-theme.css");
  const editorStablePath = path.join(skillDir, "assets", "editor-stable.js");
  const editorCompatPath = path.join(skillDir, "assets", "editor.js");

  return {
    cssBundle,
    editorBundle,
    cssPath,
    editorStablePath,
    editorCompatPath,
    cssInSync: readFileIfExists(cssPath) === cssBundle,
    editorStableInSync: readFileIfExists(editorStablePath) === editorBundle,
    editorCompatInSync: readFileIfExists(editorCompatPath) === editorBundle,
  };
}

function ensureBundledAssets(skillDir) {
  const status = getBuildStatus(skillDir);
  writeIfChanged(status.cssPath, status.cssBundle);
  writeIfChanged(status.editorStablePath, status.editorBundle);
  writeIfChanged(status.editorCompatPath, status.editorBundle);
  return {
    cssBundle: status.cssBundle,
    editorBundle: status.editorBundle,
    cssPath: status.cssPath,
    editorStablePath: status.editorStablePath,
    editorCompatPath: status.editorCompatPath,
  };
}

module.exports = {
  CSS_SOURCE_FILES,
  EDITOR_SOURCE_FILES,
  buildCssBundle,
  buildEditorBundle,
  getBuildStatus,
  ensureBundledAssets,
};
