"use strict";

const READING_PRIORITY_FAMILIES = new Set([
  "swiss-journal",
  "ledger-spec",
  "archive-paper",
  "field-atlas",
  "brief-bulletin",
  "skyline-pane",
]);

const PRODUCT_FAMILIES = new Set([
  "ops-console",
  "studio-ribbon",
  "neon-signal",
]);

const EXPRESSIVE_FAMILIES = new Set([
  "poster-brutal",
  "play-lab",
  "deck-story",
  "salon-luxe",
  "night-gallery",
  "aurora-drift",
]);

const FAMILY_HEADING_SYSTEMS = {
  "swiss-journal": "index-led",
  "ledger-spec": "index-led",
  "archive-paper": "plaque",
  "field-atlas": "icon-led",
  "brief-bulletin": "index-led",
  "skyline-pane": "index-led",
  "ops-console": "dual",
  "studio-ribbon": "plaque",
  "neon-signal": "dual",
  "poster-brutal": "plaque",
  "play-lab": "plaque",
  "deck-story": "index-led",
  "salon-luxe": "plaque",
  "night-gallery": "plaque",
  "aurora-drift": "index-led",
};

const FAMILY_VISUAL_SYSTEMS = {
  "swiss-journal": {
    mode: "reading",
    reading_priority: "reading-first",
    svg_grammar: "editorial-schematic",
    hero_scene_style: "editorial-beam",
    hero_scene_candidates: ["editorial-beam", "paper-fold", "constellation-map"],
    scene_density: "quiet",
    section_mark_style: "reading",
    mark_prominence: "low",
    divider_style: "editorial-notch",
    inline_infographic_style: "evidence-stack",
    approved_infographic_kinds: ["evidence-stack", "structure-breakdown", "path-map"],
    hero_anchor: "top-band",
    mark_placement: "caption-edge",
    graphic_quietness: "high",
    title_safe: "strict",
    frame_budget: "single",
    svg_noise_budget: "tight",
    stroke_weight: "thin",
    corner_language: "soft",
    fill_strategy: "light-tint",
    density_level: "low",
    geometry_bias: "editorial-guides",
  },
  "ledger-spec": {
    mode: "reading",
    reading_priority: "reading-first",
    svg_grammar: "ledger-wireframe",
    hero_scene_style: "editorial-beam",
    hero_scene_candidates: ["paper-fold", "editorial-beam", "signal-grid"],
    scene_density: "quiet",
    section_mark_style: "reading",
    mark_prominence: "low",
    divider_style: "editorial-notch",
    inline_infographic_style: "structure-breakdown",
    approved_infographic_kinds: ["structure-breakdown", "compare-grid", "process-track"],
    hero_anchor: "top-band",
    mark_placement: "caption-edge",
    graphic_quietness: "high",
    title_safe: "strict",
    frame_budget: "single",
    svg_noise_budget: "tight",
    stroke_weight: "thin",
    corner_language: "square",
    fill_strategy: "outline",
    density_level: "low",
    geometry_bias: "orthogonal-ledger",
  },
  "archive-paper": {
    mode: "reading",
    reading_priority: "reading-first",
    svg_grammar: "archive-plate",
    hero_scene_style: "museum-frame",
    hero_scene_candidates: ["museum-frame", "paper-fold", "editorial-beam"],
    scene_density: "quiet",
    section_mark_style: "reading",
    mark_prominence: "low",
    divider_style: "editorial-notch",
    inline_infographic_style: "evidence-stack",
    approved_infographic_kinds: ["evidence-stack", "structure-breakdown", "process-track"],
    hero_anchor: "top-band",
    mark_placement: "caption-edge",
    graphic_quietness: "high",
    title_safe: "strict",
    frame_budget: "single",
    svg_noise_budget: "tight",
    stroke_weight: "medium",
    corner_language: "framed",
    fill_strategy: "paper-fill",
    density_level: "medium",
    geometry_bias: "framed-plate",
  },
  "field-atlas": {
    mode: "reading",
    reading_priority: "reading-first",
    svg_grammar: "atlas-annotation",
    hero_scene_style: "constellation-map",
    hero_scene_candidates: ["constellation-map", "editorial-beam", "paper-fold"],
    scene_density: "quiet",
    section_mark_style: "reading",
    mark_prominence: "low",
    divider_style: "soft-stars",
    inline_infographic_style: "path-map",
    approved_infographic_kinds: ["path-map", "node-network", "evidence-stack"],
    hero_anchor: "top",
    mark_placement: "index-side",
    graphic_quietness: "high",
    title_safe: "strict",
    frame_budget: "single",
    svg_noise_budget: "tight",
    stroke_weight: "thin",
    corner_language: "soft",
    fill_strategy: "light-tint",
    density_level: "medium",
    geometry_bias: "cartographic",
  },
  "brief-bulletin": {
    mode: "reading",
    reading_priority: "reading-first",
    svg_grammar: "bulletin-editorial",
    hero_scene_style: "editorial-beam",
    hero_scene_candidates: ["editorial-beam", "paper-fold", "signal-grid"],
    scene_density: "quiet",
    section_mark_style: "reading",
    mark_prominence: "low",
    divider_style: "editorial-notch",
    inline_infographic_style: "compare-grid",
    approved_infographic_kinds: ["compare-grid", "evidence-stack", "process-track"],
    hero_anchor: "top-band",
    mark_placement: "caption-edge",
    graphic_quietness: "high",
    title_safe: "strict",
    frame_budget: "single",
    svg_noise_budget: "tight",
    stroke_weight: "thin",
    corner_language: "square",
    fill_strategy: "outline",
    density_level: "low",
    geometry_bias: "bulletin-strips",
  },
  "skyline-pane": {
    mode: "reading",
    reading_priority: "reading-first",
    svg_grammar: "skyline-wire",
    hero_scene_style: "editorial-beam",
    hero_scene_candidates: ["editorial-beam", "signal-grid", "paper-fold"],
    scene_density: "quiet",
    section_mark_style: "reading",
    mark_prominence: "low",
    divider_style: "line-orbit",
    inline_infographic_style: "structure-breakdown",
    approved_infographic_kinds: ["structure-breakdown", "compare-grid", "node-network"],
    hero_anchor: "top-band",
    mark_placement: "caption-edge",
    graphic_quietness: "high",
    title_safe: "strict",
    frame_budget: "single",
    svg_noise_budget: "tight",
    stroke_weight: "thin",
    corner_language: "soft",
    fill_strategy: "light-tint",
    density_level: "medium",
    geometry_bias: "pane-outline",
  },
  "ops-console": {
    mode: "product",
    reading_priority: "balanced",
    svg_grammar: "signal-panel",
    hero_scene_style: "signal-grid",
    hero_scene_candidates: ["signal-grid", "editorial-beam", "paper-fold"],
    scene_density: "standard",
    section_mark_style: "product",
    mark_prominence: "medium",
    divider_style: "chevron-band",
    inline_infographic_style: "node-network",
    approved_infographic_kinds: ["node-network", "compare-grid", "structure-breakdown", "process-track"],
    hero_anchor: "top-band",
    mark_placement: "title-corner",
    graphic_quietness: "medium",
    title_safe: "strict",
    frame_budget: "balanced",
    svg_noise_budget: "medium",
    stroke_weight: "medium",
    corner_language: "square",
    fill_strategy: "panel-fill",
    density_level: "high",
    geometry_bias: "console-panel",
  },
  "studio-ribbon": {
    mode: "product",
    reading_priority: "balanced",
    svg_grammar: "ribbon-plaque",
    hero_scene_style: "ribbon-flow",
    hero_scene_candidates: ["ribbon-flow", "museum-frame", "paper-fold"],
    scene_density: "standard",
    section_mark_style: "product",
    mark_prominence: "medium",
    divider_style: "fold-divider",
    inline_infographic_style: "process-track",
    approved_infographic_kinds: ["process-track", "compare-grid", "structure-breakdown"],
    hero_anchor: "top-band",
    mark_placement: "caption-edge",
    graphic_quietness: "medium",
    title_safe: "strict",
    frame_budget: "single",
    svg_noise_budget: "medium",
    stroke_weight: "medium",
    corner_language: "framed",
    fill_strategy: "ribbon-fill",
    density_level: "medium",
    geometry_bias: "ribbon-plaques",
  },
  "neon-signal": {
    mode: "product",
    reading_priority: "balanced",
    svg_grammar: "neon-signal",
    hero_scene_style: "signal-grid",
    hero_scene_candidates: ["signal-grid", "constellation-map", "ribbon-flow"],
    scene_density: "standard",
    section_mark_style: "product",
    mark_prominence: "medium",
    divider_style: "chevron-band",
    inline_infographic_style: "node-network",
    approved_infographic_kinds: ["node-network", "compare-grid", "path-map"],
    hero_anchor: "top-band",
    mark_placement: "title-corner",
    graphic_quietness: "medium",
    title_safe: "guarded",
    frame_budget: "balanced",
    svg_noise_budget: "medium",
    stroke_weight: "medium",
    corner_language: "round",
    fill_strategy: "glow-fill",
    density_level: "high",
    geometry_bias: "signal-hud",
  },
  "poster-brutal": {
    mode: "expressive",
    reading_priority: "balanced",
    svg_grammar: "poster-block",
    hero_scene_style: "ribbon-flow",
    hero_scene_candidates: ["ribbon-flow", "paper-fold", "signal-grid"],
    scene_density: "standard",
    section_mark_style: "expressive",
    mark_prominence: "medium",
    divider_style: "fold-divider",
    inline_infographic_style: "compare-grid",
    approved_infographic_kinds: ["compare-grid", "structure-breakdown", "process-track"],
    hero_anchor: "top",
    mark_placement: "title-corner",
    graphic_quietness: "low",
    title_safe: "guarded",
    frame_budget: "balanced",
    svg_noise_budget: "open",
    stroke_weight: "heavy",
    corner_language: "square",
    fill_strategy: "solid-fill",
    density_level: "high",
    geometry_bias: "block-poster",
  },
  "play-lab": {
    mode: "expressive",
    reading_priority: "balanced",
    svg_grammar: "play-symbolic",
    hero_scene_style: "constellation-map",
    hero_scene_candidates: ["constellation-map", "ribbon-flow", "paper-fold"],
    scene_density: "standard",
    section_mark_style: "expressive",
    mark_prominence: "medium",
    divider_style: "soft-stars",
    inline_infographic_style: "structure-breakdown",
    approved_infographic_kinds: ["structure-breakdown", "node-network", "compare-grid"],
    hero_anchor: "top-band",
    mark_placement: "title-corner",
    graphic_quietness: "low",
    title_safe: "guarded",
    frame_budget: "balanced",
    svg_noise_budget: "open",
    stroke_weight: "medium",
    corner_language: "round",
    fill_strategy: "solid-fill",
    density_level: "high",
    geometry_bias: "playful-symbols",
  },
  "deck-story": {
    mode: "expressive",
    reading_priority: "balanced",
    svg_grammar: "story-ribbon",
    hero_scene_style: "ribbon-flow",
    hero_scene_candidates: ["ribbon-flow", "museum-frame", "editorial-beam"],
    scene_density: "standard",
    section_mark_style: "expressive",
    mark_prominence: "medium",
    divider_style: "fold-divider",
    inline_infographic_style: "process-track",
    approved_infographic_kinds: ["process-track", "evidence-stack", "compare-grid"],
    hero_anchor: "top-band",
    mark_placement: "caption-edge",
    graphic_quietness: "medium",
    title_safe: "guarded",
    frame_budget: "balanced",
    svg_noise_budget: "medium",
    stroke_weight: "medium",
    corner_language: "soft",
    fill_strategy: "ribbon-fill",
    density_level: "medium",
    geometry_bias: "story-panels",
  },
  "salon-luxe": {
    mode: "expressive",
    reading_priority: "balanced",
    svg_grammar: "salon-emblem",
    hero_scene_style: "museum-frame",
    hero_scene_candidates: ["museum-frame", "ribbon-flow", "editorial-beam"],
    scene_density: "standard",
    section_mark_style: "expressive",
    mark_prominence: "medium",
    divider_style: "fold-divider",
    inline_infographic_style: "evidence-stack",
    approved_infographic_kinds: ["evidence-stack", "structure-breakdown", "compare-grid"],
    hero_anchor: "top-band",
    mark_placement: "title-corner",
    graphic_quietness: "medium",
    title_safe: "guarded",
    frame_budget: "single",
    svg_noise_budget: "medium",
    stroke_weight: "medium",
    corner_language: "framed",
    fill_strategy: "paper-fill",
    density_level: "medium",
    geometry_bias: "salon-cartouche",
  },
  "night-gallery": {
    mode: "expressive",
    reading_priority: "balanced",
    svg_grammar: "gallery-frame",
    hero_scene_style: "museum-frame",
    hero_scene_candidates: ["museum-frame", "signal-grid", "editorial-beam"],
    scene_density: "standard",
    section_mark_style: "expressive",
    mark_prominence: "medium",
    divider_style: "fold-divider",
    inline_infographic_style: "structure-breakdown",
    approved_infographic_kinds: ["structure-breakdown", "compare-grid", "node-network"],
    hero_anchor: "top-band",
    mark_placement: "title-corner",
    graphic_quietness: "medium",
    title_safe: "guarded",
    frame_budget: "single",
    svg_noise_budget: "medium",
    stroke_weight: "medium",
    corner_language: "framed",
    fill_strategy: "outline",
    density_level: "medium",
    geometry_bias: "gallery-frame",
  },
  "aurora-drift": {
    mode: "expressive",
    reading_priority: "balanced",
    svg_grammar: "aurora-orbit",
    hero_scene_style: "constellation-map",
    hero_scene_candidates: ["constellation-map", "ribbon-flow", "editorial-beam"],
    scene_density: "standard",
    section_mark_style: "expressive",
    mark_prominence: "medium",
    divider_style: "soft-stars",
    inline_infographic_style: "path-map",
    approved_infographic_kinds: ["path-map", "node-network", "structure-breakdown"],
    hero_anchor: "top-band",
    mark_placement: "index-side",
    graphic_quietness: "medium",
    title_safe: "strict",
    frame_budget: "single",
    svg_noise_budget: "medium",
    stroke_weight: "thin",
    corner_language: "round",
    fill_strategy: "light-tint",
    density_level: "medium",
    geometry_bias: "orbital-flow",
  },
};

module.exports = {
  READING_PRIORITY_FAMILIES,
  PRODUCT_FAMILIES,
  EXPRESSIVE_FAMILIES,
  FAMILY_HEADING_SYSTEMS,
  FAMILY_VISUAL_SYSTEMS,
};
